---
title: "HODEN Fall 2020"
output:
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r setup 1, include=FALSE}
library(tidyverse)
library(rio)
library(here)
library(colorblindr)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(SCVA)
library(patchwork)


theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )

brief_self <- import(here("data", "HODEN_brief_self.xlsx"),
               setclass = "tbl_df") 

```

## BRIEF-A Self-Report

```{r, include=FALSE}
brief_tbl <- function(df) {
  df %>% 
  reactable(
    columns = list(
      `Scale/Index` = colDef(align = "center"),
      `Raw Score` = colDef(name = "Raw Score",
                           align = "center"),
      `T-Score` = colDef(name = "T-Score",
                         align = "center"),
      `Percentile Rank` = colDef(name = "Percentile Rank",
                                align = "center")),
    pagination = FALSE,
    striped = TRUE,
    outlined = TRUE,
    compact = TRUE,
    highlight = TRUE,
    bordered = TRUE,
    #searchable = TRUE,
    height = 600,
    width = 500)
}

brief_tbl(brief_self)
```


```{r, include=TRUE, fig.height=8, fig.width=10}
brief_tbl(brief_self)
```